### ISSUE TITLE
Hello world in SwiftSpace

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/SwiftSpace#1]
Hi @michele-loreti @fede-Raider 

Would it be possible to create a Hello World example as we have done for the rest of the languages? See:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/hello.md

**Comment by fede-Raider** [comment]
Example "HelloWorld" added to the repository:
https://github.com/pSpaces/SwiftSpace/blob/master/SwiftSpace/Examples/HelloWorld.swift

**Comment by albertolluch** [comment]
Thanks, I just checked it and integrated it "hello world" page:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/hello.md
