### ISSUE TITLE
Naming table

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/SwiftSpace#3]
Column Swift of this table needs to be filled

https://github.com/pSpaces/Programming-with-Spaces/blob/master/naming.md

**Comment by fede-Raider** [comment]
I have made a commit for Swift language.

**Comment by albertolluch** [comment]
Thanks @fede-Raider I merged your changes and closed the issue.

@michele-loreti @fede-Raider what is a `TreeSpace`? It is not documented in the guide for programmers or in the semantics. Is it a different implementation for the same behaviour as SequentialSpace?

**Comment by fede-Raider** [comment]
I'm sorry, "TreeSpace" is a RandomSpace that is implemented through a tree structure to get a better performance.

What is the difference between a QueueSpace and a SequentialSpace? 
I'm not sure where I should put the "TupleList".

**Comment by albertolluch** [comment]
So TreeSpace has a probabilistic behaviour? Se description of RandomSpace here:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/guide.md#core-space-api

Regarding the difference between QueueSpace and SequentialSpace, you can read the informal description here:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/guide.md#core-space-api

The main difference is that QueueSpace behaves like a pure fifo queue: get/query operations fail if the head does not match the given pattern. Instead in a SequentialSpace, the operations may succeed if there is another tuple behind the head. In other words, in QueueSpace on only sees the head, while in SequentialSpace all tuples are considered in fifo order.

**Comment by fede-Raider** [comment]
TupleTree stores tuples with a tree structure and we can't know if the returned tuple that matches with specific template is the first/last inserted.
In general we can not know the order in which the tuples were inserted.

![image](https://user-images.githubusercontent.com/9324985/34524930-90acdec6-f09d-11e7-80d9-e7443a5bfe58.png)
Example of TupleTree after:
-put(["abc", 2, 5])
-put(["abc"])
-put(["abc"])
-put(["abc", "b"])

So TupleTree is a RandomSpace and TupleList is a SequentialSpace.

**Comment by albertolluch** [comment]
I see, thanks for the clarification.

So a TreeSpace is a tuple space that conforms to the NonDeterministic behaviour (they all should) and that is good.

However, it can't be called RandomSpace because the behaviour is actually deterministic and made on a pseudo-random generator. For example, consecutive queries on the same TreeSpace return the same tuple. This should not happen in a RandomSpace. I guess we need a name for this kind of behaviour. For now we could just call it `TreeSpace`.
